model_name: "flux-dev"
data_config:
  train_batch_size: 1
  num_workers: 4
  img_size: 512
  img_dir: images
  learnable_property: "object"
  repeats: 100
report_to: tensorboard
train_batch_size: 1
output_dir: saves
max_train_steps: 1000
learning_rate: 1e-5
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 2500
checkpoints_total_limit: 10
tracker_project_name: finetune_test
resume_from_checkpoint: latest
gradient_accumulation_steps: 4
validation_prompt: "A construction site in the style of <animation>"
validation_steps: 300
guidance: 4
num_validation_images: 1
placeholder_token: "<animation>"
num_vectors: 32
initializer_token: "animation"
